version: '3.8'

services:
  auth-api:
    container_name: yumaidentity_api
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - auth-network
    depends_on:
      mssql: 
        condition: service_healthy 
    restart: 
      on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=YumaIdentity;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__AccessTokenExpirationMinutes=${Jwt__AccessTokenExpirationMinutes}
      - Jwt__RefreshTokenExpirationDays=${Jwt__RefreshTokenExpirationDays}
      - AdminSeed__AdminClientId=${AdminSeed__AdminClientId}
      - AdminSeed__AdminClientName=${AdminSeed__AdminClientName}
      - AdminSeed__AdminClientSecret=${AdminSeed__AdminClientSecret}
      - AdminSeed__SuperAdminEmail=${AdminSeed__SuperAdminEmail}
      - AdminSeed__SuperAdminPassword=${AdminSeed__SuperAdminPassword}
      - AdminSeed__AdminDashboardUrl=${AdminSeed__AdminDashboardUrl:-http://localhost:3000}
      - SmtpSettings__Host=${SMTP_HOST:-mailpit}
      - SmtpSettings__Port=${SMTP_PORT:-1025}
      - SmtpSettings__Username=${SMTP_USER}
      - SmtpSettings__Password=${SMTP_PASS}
      - SmtpSettings__SenderName=${SMTP_SENDER_NAME:-YumaIdentity}
      - SmtpSettings__SenderEmail=${SMTP_SENDER_EMAIL:-noreply@yumaidentity.com}

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: yumaidentity_mssql_db
    user: root
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}" 
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -Q 'SELECT 1' -C || exit 1"] 
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    container_name: yumaidentity_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" 
      - "1025:1025"
    networks:
      - auth-network

  loki:
    image: grafana/loki:main-688dd20
    container_name: yumaidentity_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - auth-network

  grafana:
    image: grafana/grafana:12.1
    container_name: yumaidentity_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yuma
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - auth-network

volumes:
  mssql-data:

networks:
  auth-network:
    driver: bridge